spring:
  application:
    name: Xiaomi-store-project
  mail:
    host: smtp.163.com
    username: ayor1337@163.com
    password: WEWshPE62xYFUTxr
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_store
    username: root
    password: zhx197709
  data:
    redis:
      host: localhost
      port: 6379
  security:
    jwt:
      secret-key: qwert123456
      expire: 7
  minio:
    endpoint: http://localhost:9000
    access-key: admin
    secret-key: qwert123
    bucket: example
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /mistore
    listener:
      simple:
        acknowledge-mode: manual
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity.pojo
server:
  port: 9090
