name: MiStoreDevEnvironment
services:
  mysql:
    container_name: mysql
    build:
      context: ./image/mysql
      dockerfile: Dockerfile
    #      image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - /mi_store/mysql:/var/lib/mysql
    env_file:
      - ./environment/mysql.env
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped
    networks:
      - store-project
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - /mi_store/redis:/data
    networks:
      - store-project
  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /mi_store/minio/data:/data
      - /mi_store/minio/config:/root/.minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: qwert123
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - store-project
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    restart: unless-stopped
    networks:
      - store-project

networks:
  store-project:
